//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppMVCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELMLastDayProductionModel
    {
        public System.DateTime Date_ { get; set; }
        public float Oilvol { get; set; }
        public float LPGvol { get; set; }
        public float CondVol { get; set; }
    
        public virtual HBNSLastDayProductionModel HBNSLastDayProductionModel { get; set; }
    }
}
