//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppMVCC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LastDayProductionEntities : DbContext
    {
        public LastDayProductionEntities()
            : base("name=LastDayProductionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ELMLastDayProductionModel> ELMLastDayProductionModel { get; set; }
        public virtual DbSet<HBNSLastDayProductionModel> HBNSLastDayProductionModel { get; set; }
    }
}
